from os import getenv

from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = getenv('OPENAI_API_KEY')
OPENAI_MODEL_NAME = getenv('OPENAI_MODEL_NAME')
OPENAI_EMBEDDING_MODEL_NAME = getenv('OPENAI_EMBEDDING_MODEL_NAME')

CHROMA_DB_HOST = getenv('CHROMA_DB_HOST')
CHROMA_DB_PORT = getenv('CHROMA_DB_PORT')

PINECONE_API_KEY = getenv('PINECONE_API_KEY')
PINECONE_ENVIRONMENT = getenv('PINECONE_ENVIRONMENT')
PINECONE_INDEX_NAME = getenv('PINECONE_INDEX_NAME')

UPSTASH_REDIS_REST_URL = getenv('UPSTASH_REDIS_REST_URL')
UPSTASH_REDIS_REST_TOKEN = getenv('UPSTASH_REDIS_REST_TOKEN')